services:
  static-builder:
    image: node:23-alpine
    container_name: ReTargetStaticBuilder
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run build"
    networks:
      - retarget_network
    restart: "no"

  static-server:
    image: node:23-alpine
    container_name: ReTargetStaticServer
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    command: sh -c "cd server && npm install && node index.js"
    depends_on:
      - static-builder
    networks:
      - retarget_network

networks:
  retarget_network:
    external: true
