services:
  static-builder:
    image: node:23-alpine
    container_name: ReTargetStaticBuilder
    working_dir: /app
    user: "1000:1000"
    environment:
      - PRODUCTION: "true"
    volumes:
      - .:/app
    command: sh -c "npm install --production && npm run build"
    networks:
      - retarget_network
    restart: "no"

networks:
  retarget_network:
    external: true
