version: '3.8'

services:
  app:
    image: node:16
    container_name: static_server
    working_dir: /app
    volumes:
      - ..:/app
    ports:
      - "${PORT}:${PORT}"
    command: sh -c "cd ./server && npm install && node index.js"
